export const RESEARCH_LOOP_STEPS = [
  "CREATE_RESEARCH_DB",
  "INPUT_RESEARCH_QUESTION_HYPOTHESIS",
  "BUILD_RESEARCH_SPECIFICATION",
  "PLAN_RESEARCH",
  "EXECUTE_TOOLS",
  "NORMALIZE_DATA",
  "BUILD_VECTOR_INDEX",
  "BUILD_ONTOLOGY_GRAPH",
  "REASON_AND_VALIDATE",
  "SYNTHESIZE_AND_EVALUATE",
  "DECIDE_CONTINUATION",
  "FINALIZE_OUTPUTS"
] as const;

export type ResearchLoopStep = (typeof RESEARCH_LOOP_STEPS)[number];
