import { createId, nowIso } from "../shared/ids.js";
import type { OpenCodeRunInput, ResearchArtifact, ToolRun } from "../shared/types.js";
import type { ResearchTool, ResearchToolResult } from "./researchToolTypes.js";

export class ArtifactWriterTool implements ResearchTool {
  name = "ArtifactWriterTool";

  async run(input: OpenCodeRunInput): Promise<ResearchToolResult> {
    const startedAt = nowIso();
    const completedAt = nowIso();
    const lines = [`# Iteration ${input.iteration} Research Note`, "", "## Objective", input.project.goal, "", "## Current Questions"];
    for (const item of input.questions) lines.push(`- ${item.text}`);
    lines.push("", "## Hypotheses");
    for (const item of input.hypotheses) lines.push(`- ${item.statement} (${item.status}, confidence=${item.confidence})`);
    lines.push(
      "",
      "## RAG Summary",
      input.ragContext?.summary ?? "No RAG context has been built yet.",
      "",
      "## Traceability",
      "- This note is an internal artifact generated by AetherOps.",
      "- It must not be treated as external evidence for hypothesis support."
    );
    const content = lines.join("\n");
    const artifact: ResearchArtifact = {
      id: createId("artifact"),
      projectId: input.project.id,
      category: "generated_artifact",
      title: `Iteration ${input.iteration} research note`,
      relativePath: `artifacts/iteration-${input.iteration}/research-note.md`,
      mimeType: "text/markdown",
      summary: "Internal iteration note summarizing questions, hypotheses, RAG context, and limitations.",
      content,
      createdAt: completedAt
    };
    return {
      toolRun: completedToolRun(input, this.name, startedAt, completedAt, { relativePath: artifact.relativePath }, { artifactId: artifact.id }),
      evidence: [],
      artifacts: [artifact],
      sources: []
    };
  }
}

function completedToolRun(input: OpenCodeRunInput, toolName: string, startedAt: string, completedAt: string, toolInput: unknown, output: unknown): ToolRun {
  return {
    id: createId("tool"),
    projectId: input.project.id,
    iteration: input.iteration,
    toolName,
    input: toolInput,
    output,
    status: "completed",
    startedAt,
    completedAt
  };
}
